name: Main Workflow

on:
  push:
    branches: [ main ]
    
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: Checkout 🛎️
      uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Installing packages 👍
      run: npm ci
    - name: Build static website 🔧
      run: npm run build
    - run: npm run export
      
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@4.1.1
      with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: out # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch
        
    - name: Send a message to Microsoft Teams
      uses: aliencube/microsoft-teams-actions@v0.8.0
      with:
        webhook_uri: https://viaucdk.webhook.office.com/webhookb2/9f590991-f6d7-4f55-a767-55e8c7f6c82e@97e1982b-375c-460e-9071-9067de86388b/IncomingWebhook/9d1e1c27ae2143b69ec15ef3eef18ecc/faefbb04-5dce-4562-a8df-9ccd3a4025e1
        title: Main branch  
        summary: Main branch - pull request 
        text: A new pull request to main branch.

 
  
    
